POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name" :"Hasan",
    "username"  :"hasan91",
    "password": "hasan123"
}


#### 

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name" :"ilhaan",
    "username"  :"ilhaan22",
    "password": "ilhaan123"
}

#### 

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name" :"ilhaan3",
    "username"  :"ilhaan223",
    "password": "ilhaan1233"
}